function results = dem_load_all(dataDir, varargin)
% Scan a directory for *.mat files generated by Pos_Vel_Extrace_v3.m and
% extract DEM observables for each. Returns a struct array, one element
% per file, sorted by phi (ascending).
%
% Use Name-Value pairs to forward options to dem_extract_run.
%
% Example:
%   res = dem_load_all('D:/data/PosVel_data', 'L', 4.0, 'd_force', 0.08);

    p = inputParser;
    p.KeepUnmatched = true;
    p.addParameter('pattern', 'Data_*.mat');
    p.addParameter('verbose', true);
    p.parse(varargin{:});
    extraArgs = unmatched_to_pv(p.Unmatched);

    files = dir(fullfile(dataDir, p.Results.pattern));
    if isempty(files)
        % also try recursive
        files = dir(fullfile(dataDir, '**', p.Results.pattern));
    end
    if isempty(files)
        error('dem_load_all:noFiles', ...
            'No files matching %s under %s', p.Results.pattern, dataDir);
    end

    results = [];
    for k = 1:numel(files)
        fp = fullfile(files(k).folder, files(k).name);
        if p.Results.verbose
            fprintf('[%d/%d] %s\n', k, numel(files), files(k).name);
        end
        try
            r = dem_extract_run(fp, extraArgs{:});
            if isempty(results)
                results = r;
            else
                results(end+1) = r; %#ok<AGROW>
            end
        catch ME
            warning('dem_load_all:fileFailed', ...
                'Skipping %s : %s', files(k).name, ME.message);
        end
    end

    % Sort by phi
    if ~isempty(results)
        phis = [results.phi];
        [~, idx] = sort(phis);
        results = results(idx);
    end
end

function pv = unmatched_to_pv(s)
    fn = fieldnames(s);
    pv = cell(1, 2*numel(fn));
    for i = 1:numel(fn)
        pv{2*i-1} = fn{i};
        pv{2*i}   = s.(fn{i});
    end
end
